### ISSUE TITLE
can not install on ubuntu budgie 17.04 through pip or pip3 also test can't run from ./install_remove install

### ISSUE THREAD

**Issue by 243750496** [hvdwolf/pyExifToolGUI#35]
```
atc@ATC:~/pyExifToolGUI-0.5$ sudo pip install '/home/atc/Downloads/Compressed/pyExifToolGUI-0.5.tar.gz' 
The directory '/home/atc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/atc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/atc/Downloads/Compressed/pyExifToolGUI-0.5.tar.gz
Installing collected packages: pyexiftoolgui
  Running setup.py install for pyexiftoolgui ... done
Successfully installed pyexiftoolgui-0.5
atc@ATC:~/pyExifToolGUI-0.5$ pyexiftoolgui
Real folder where this launcher was started from: /usr/local/bin
We are not running from our source folder. Are we running from /usr/bin?

```

and btw: if i installed as installation.txt said it will show up  an error!!!
and if i run sudo ./install_remove.py remove it will leave a build folder with super user access, do that means uninstall correctly???(all i need to do is just rm -rf it??)

![bug](https://user-images.githubusercontent.com/6311930/28601521-451e1ece-71eb-11e7-902f-c85d04fa657b.png)

**Comment by hvdwolf** [comment]
Hi,
As far as I know 17.04 is called Zesty Zapus, but that aside.

I do not maintain a pip package. If someone else created that, then that's a surprise for me as well.
The setup.py currently is actually untested for pip.

The INSTALLATION.TXT mentions:

Installation on Linux
=====================
Dependencies (Meaning that you need to install them yourself):
- python: part of every linux system, so always available, but >=2.6 required.
- Qt >=4.6: Qt is available for all major distributions but in case it is not you can download it from http://qt-project.org/downloads
- pyside: Install via your distribution's package manager. Otherwise download it from www.pyside.org
- python-pyside (qtcore, qtgui and qtuitools are required): Install via your distribution's package manager. 
  Otherwise download it from www.pyside.org
- ExifTool: Install via your distribution's package manager.

Installation:
= DO NOT RUN setup.py DIRECTLY ! =
- Untar the package to some folder (You obviously did that already if you are reading this).
- Open a terminal and move into the folder where you untarred the pyExifToolGui-x.y.tgz
- Run the setup script from the command line with "sudo ./install_remove.py install".
- pyExifToolGUI will be installed and you should have an icon.
- Start and enjoy.



did you do that? including the exiftool install?
