### ISSUE TITLE
Can not resize the program window

### ISSUE THREAD

**Issue by core45** [hvdwolf/pyExifToolGUI#46]
I have just downloaded this great tool but I have one problem - I can't resize the program window.
My system is Ubuntu 18.04

**Comment by hvdwolf** [comment]
That is indeed an omission of the program. Pyside had a few glitches that when resizing a window the other window objects got corrupted.That is why the window is fixed.
I stopped developing pyExiftoolGui a long time ago.
Last year I started on jExifToolGui, a java version. Due to personal reasons I stopped it, but just started it again.
Apart from the renaming it does the same.
See https://github.com/hvdwolf/jExifToolGUI
and https://hvdwolf.github.io/jExifToolGUI/
